from .otps import OtpsViewSet
from .auths import AuthsViewSet
from .artists import ArtistsViewSet
from .passwords import PasswordsViewSet
from .location import LocationViewset
from .bank_list import BankListViewSet
from .accounts import AccountViewSet
from .upload_songs import UploadSongsViewSet
from .analytics import DataAnalyticsViewSet
