DROP TABLE db_location CASCADE;
DROP TABLE db_account;
DROP TABLE db_artist;
DROP TABLE django_session;
DROP TABLE django_migrations;
DROP TABLE django_admin_log;
DROP TABLE authtoken_token;
DROP TABLE db_user;
DROP TABLE auth_group_permissions;
DROP TABLE auth_permission;
DROP TABLE auth_group;
DROP TABLE django_content_type;