# Generated by Django 3.1.2 on 2020-11-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='number_of_songs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='number_of_streams',
            field=models.IntegerField(default=0),
        ),
    ]
